server:
  port: 9090

# Database
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xyzcar
    username: root
    password: 1234

# JPA-HIBERNATE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

# OAuth2 Configuration
security:
  oauth2:
    client:
      clientId: 319406134392526
      clientSecret: fdba2fcb0758034c13ce3f3f1b9fa18c
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

    
 